openapi: 3.0.0
info:
  version: 1.0.0
  title: Customer Review API
  description: API that handles Customer Reivews

security:
  - BasicAuth: []

path:
  /reviews:
    get:
      description: Returns a list of customers reviews
      parameters: 
        # leave blank for now
        # figure out components first
      responses:
        '200':
          description: Successfully returned a list of customer reviews
          content:
            application/json:
              schema:
                type: array
                items:
                  # figure out components for this line
        '400':
          # figure out components for this line
    post:
      description: Allows user to post review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              # figure out components for this line
        responses:
        '200':
          description: Successfully created a new artist
        '400':
            # figure out components for this line
    delete:
      description: Deletes all reviews
      responses:
        '200':
          description: Successfully deleted all reviews
        '400':
          description: Invalid request

  /reviews/{id}: #Michael
    get:
      summary: Retrieve a specific review
      parameters: # Can change later
        - name: id
          in: path
          description: ID of the review to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully retrieved the specified review
          content:
            application/json:
              schema:
                $ref: #'#/components/schemas/Review'
    delete:
      summary: Deletes review at specified ID
      parameters:
        - name: id
          in: path
          description: ID of the review to delete
          requred: true
          schema:
            type: integer
      responses:
        '200':
          description: Review at given ID successfully deleted
        '400':
          description: Invalid request

  /reviews: # Michael
    get:
      summary: Retrieve reviews based on query parameters
      parameters: # Can change later
        - name: userID
          in: query
          description: ID of the user to retrieve reviews for
          required: false
          schema:
            type: integer
        - name: restaurantsID
          in: query
          description: ID of the restaurant to retrieve reviews for
          required: false
          schema:
            type: integer
        - name: restaruantRating
          in: query
          description: Rating of the restaurant to retrieve reviews for
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Successfully retrieved the reviews based on the specified rating
          content:
            application/json:
              schema:
                $ref: #'#/components/schemas/Review'

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
