openapi: 3.0.0
info:
  version: 1.0.0
  title: Customer Review API
  description: API that handles Customer Reivews

security:
  - BasicAuth: []

paths:
  /reviews:
    get:
      description: Returns a list of customers reviews
      parameters: 
        # leave blank for now
        # figure out components first
        # note from emma: i think this does not have any parameters :)
      responses:
        '200':
          description: Successfully returned a list of customer reviews
          content:
            application/json:
              schema:
                type: array
                items:
                  # figure out components for this line
        '400':
          $ref: '#components/responses/400Error'
    #removed unnecessary POST request here -- whoever sees this can delete this line :)
    delete:
      description: Deletes all reviews
      responses:
        '204':
          description: Successfully deleted all reviews
        '400':
          $ref: '#components/responses/400Error'
        '404':
          description: Reviews not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404Error'

  /reviews/{id}: #Michael
    get:
      description: Retrieve a specific review
      parameters: # Can change later
        - $ref: '#components/parameters/ReviewID' #changed parameter to a component - Emma :)
      responses:
        '200':
          description: Successfully retrieved the specified review
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '400':
          $ref: '#components/responses/400Error'
    patch: #Torrence
      description: "edit to existing review"
      parameters:
        - $ref: '#components/parameters/ReviewID'
      responses:
        '200':
          description: 'Update successful'
          content:
            application/json:
              schema:
                type: object
                properties: 
                  message: 
                    type: string
        '400':
          $ref: '#components/responses/400Error'
        '403':
          description: Not permitted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: review not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404Error'
    delete: #Emma
      description: Deletes review at specified ID
      parameters:
        - $ref: '#components/parameters/ReviewID'
      responses:
        '204':
          description: Review at given ID was successfully deleted.
        '400':
          $ref: '#components/responses/400Error'
        '404':
          description: Review with given ID was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404Error'

  /reviews/restaruant/{id}: # Michael
    get:
      description: "Retrieve all reviews for a restaurant"
      parameters:
        - $ref: '#components/parameters/RestaurantID'
        - in: query
          name: restaruantRating
          schema:
            type: integer
          required: false
          description: "Rating of the restaurant to retrieve reviews for"
      responses:
        '200':
          description: Successfully list the specified review
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '400':
          $ref: '#components/responses/400Error'
      post: # Dhruvisha
        description: Lets a customer post a review for a restaurant
          requestBody:
          required: true
          content:
            application/json:
              schema:
                type: string
        parameters:
        - $ref: '#components/parameters/RestaurantID'
        responses:
          '200':
            description: Successfully added a new review for a restaurant 
          '400':
            $ref: '#components/responses/400Error'
      delete:
        description: Deletes all reviews for a restaurant
        parameters:
        - $ref: '#components/parameters/RestaurantID'
        responses:
          '204':
            description: Successfully deleted all reviews for given restaurant
          '400':
            $ref: '#components/responses/400Error'
          '404':
            description: Restaurant reviews not found
            content:
            application/json:
              schema:
                $ref: '#/components/schemas/404Error'


  /reviews/driver/{id}:  # Dhruvisha & Torrence
    get:
      description: Retrieve all reviews for a driver
        requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      parameters:
        - $ref: '#components/parameters/DriverID'
        - in: query
          name: driverRating
          schema:
            type: integer
          required: false
          description: "Rating of the driver to retrieve reviews for"
      responses:
        '200':
          descirption: Successfully retrieved reviews
          schema:
            type: object
            properties:
              reviews:
              type: string
        '400':
          $ref: "#/components/responses/400Error"
    post:
      description: Add a review for a driver
        requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      parameters:
        - $ref: '#components/parameters/DriverID'
      responses:
        '200':
          description: Successfully added a new review for a driver 
        '400':
          $ref: '#components/responses/400Error'
    delete:
      description: Deletes all reviews for a driver
      parameters:
        - $ref: '#components/parameters/DriverID'
      responses:
        '204':
          description: Successfully deleted all reviews for given driver
        '400':
          $ref: '#components/responses/400Error'
        '404':
          description: Driver reviews not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404Error'

  /reviews/{id}/comments:
    get:
      description: retrieves all comments for an existing review
        requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      parameters:
        - $ref: '#components/parameters/ReviewID'
      responses:
        '200':
          descirption: Successfully retrieved reviews
          schema:
            type: object
            properties:
              reviews:
              type: string
        '400':
          $ref: '#components/responses/400Error'
        '403':
          description: Not permitted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: review not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMsg'
    post: # Dhruvisha
      description: Add a comment for an existing review
        requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      parameters:
        - $ref: '#components/parameters/ReviewID'
      responses:
        '200':
          description: Successfully added a new comment for an existing review
        '400':
          $ref: '#components/responses/400Error'
    delete: #TODO

  /reviews/{id}/comments/{id}:
    get: #TODO (everything but params)
      parameters:
        - $ref: '#components/parameters/ReviewID'
        - $ref: '#components/parameters/CommentID'
    patch: #TODO (everything but params)
      parameters:
        - $ref: '#components/parameters/ReviewID'
        - $ref: '#components/parameters/CommentID'
    delete: #TODO (everything but params)
      parameters:
        - $ref: '#components/parameters/ReviewID'
        - $ref: '#components/parameters/CommentID'

  /reviews/user/{id}: # Michael
    get:
      description: "Retrieve all reviews from a specific user"
      parameters:
        - $ref: '#components/parameters/UserID'
      responses:
        '200':
          description: Successfully list the review from the specified user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewList'
        '400':
          $ref: '#/components/responses/400Error'
    delete: #TODO

  /health:  #Emma --> unsure if this is exactly what she wants for this or not
    get:
      description: Gets health of API
      responses:
        '200':
          description: Successful call to health
          content:
            application/json:
              schema:
                type: object
                properties:
                  server_health:
                    type: string

#TODO: make more components probably... any time we are
#getting back a review we should have a review component
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  
  schemas:
    ErrorMsg:
      type: object
      properties:   
        message:
          type: string
    Review:
      type: object
      required:
      - Review-id
      - rating
      - userId
      - driver-id/restuarant-id
      - comment
      - published/date
      properties:
        id:
          type: string
        rating: 
          type: double
        comment:
          type: string
        user:
          type: string
        driver:
          type: string
        restuarant:
          type: string
        published:
          type: int
    ReviewList:
      type: array
      items:
        $ref: '#/components/schemas/Review'
  #TODO: make a Reviews scheme
  #TODO: make a SingleReview scheme
  
  parameters:
    ReviewID:
      name: review-id
      in: path
      description: ID of the review
      required: true
      schema:
        type: integer
    CommentID:
      name: comment-id
      in: path
      description: ID of the comment
      required: true
      schema:
        type: integer
    RestaurantID:
      name: restaurant-id
      in: path
      description: ID of the restaurant
      required: true
      schema:
        type: integer
    DriverID:
      name: driver-id
      in: path
      description: ID of the driver
      required: true
      schema:
        type: integer
    UserID:
      name: user-id
      in: path
      description: ID of the user
      required: true
      schema:
        type: integer

  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    404Error:
      description: Review not found with given ID
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string