openapi: 3.0.0
info:
  version: 1.0.0
  title: Customer Review API
  description: API that handles Customer Reivews

security:
  - BasicAuth: []

path:
  /reviews:
    get:
      description: Returns a list of customers reviews
      parameters: 
        # leave blank for now
        # figure out components first
      responses:
        '200':
          description: Successfully returned a list of customer reviews
          content:
            application/json:
              schema:
                type: array
                items:
                  # figure out components for this line
        '400':
          # figure out components for this line
    post:
      description: Allows user to post review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              # figure out components for this line
        responses:
        '200':
          description: Successfully created a new artist
        '400':
            # figure out components for this line
    delete:
      description: Deletes all reviews
      responses:
        '204':
          description: Successfully deleted all reviews
        '400':
          $ref: '#components/responses/400Error'
        '404':
          description: Reviews not found

  /reviews/{id}: #Michael
    get:
      summary: Retrieve a specific review
      parameters: # Can change later
        - $ref: '#components/parameters/ReviewID' #changed parameter to a component - Emma :)
      responses:
        '200':
          description: Successfully retrieved the specified review
          content:
            application/json:
              schema:
                $ref: #'#/components/schemas/Review'
    delete: #Emma
      summary: Deletes review at specified ID
      parameters:
        - $ref: '#components/parameters/ReviewID'
      responses:
        '204':
          description: Review at given ID was successfully deleted.
        '400':
          $ref: '#components/responses/400Error'
        '404':
          description: Review with given ID was not found.

  /reviews: # Michael
    get:
      summary: Retrieve reviews based on query parameters
      parameters: # Can change later
        - name: userID
          in: query
          description: ID of the user to retrieve reviews for
          required: false
          schema:
            type: integer
        - name: restaurantsID
          in: query
          description: ID of the restaurant to retrieve reviews for
          required: false
          schema:
            type: integer
        - name: restaruantRating
          in: query
          description: Rating of the restaurant to retrieve reviews for
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Successfully retrieved the reviews based on the specified rating
          content:
            application/json:
              schema:
                $ref: #'#/components/schemas/Review'
  /health:  #Emma --> unsure if this is exactly what she wants for this or not
    get:
      summary: Gets health of API
        responses:
          '200':
            description: Successful call to health
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    server_health:
                      type: string

/reviews: # Dhruvisha
    post:
      description: Lets a customer post a review for a restaurant
        requestBody:
        required: true
        content:
          application/json:
            schema:
              # figure out components for this line
        responses:
        '200':
          description: Successfully added a new review for a restaurant 
        '400':
            # figure out components for this line

/reviews: # Dhruvisha
    post:
      description: Lets a customer post a review for a driver
        requestBody:
        required: true
        content:
          application/json:
            schema:
              # figure out components for this line
        responses:
        '200':
          description: Successfully added a new review for a driver 
        '400':
            # figure out components for this line

/reviews: # Dhruvisha
    post:
      description: Lets a customer post a comment for an existing review
        requestBody:
        required: true
        content:
          application/json:
            schema:
              # figure out components for this line
        responses:
        '200':
          description: Successfully added a new comment for an existing review
        '400':
            # figure out components for this line


              

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  
  parameters:
    ReviewID:
      name: id
      in: path
      description: ID of the review to delete
      required: true
      schema:
        type: integer

  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

